In [24]:
import numpy as np
import pandas as pd

In [25]:
a = np.arange(1,11)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [26]:
#menambahkan jumlah index
a+1 

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [27]:
#1 dibagi value dari setiap index
1/a

array([1.        , 0.5       , 0.33333333, 0.25      , 0.2       ,
       0.16666667, 0.14285714, 0.125     , 0.11111111, 0.1       ])

In [28]:
#menghitung kuadrat dari value di setiap index
a*a

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [29]:
b = a.copy()
c = b.reshape(2,5)
c

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [30]:
#menghitung kuadrat dari setiap value index
c**2

array([[  1,   4,   9,  16,  25],
       [ 36,  49,  64,  81, 100]], dtype=int32)

In [31]:
#mengalikan 2 array, jumlah kolomnya harus sama
d = np.array([10,20,30,40,50])
c*d

array([[ 10,  40,  90, 160, 250],
       [ 60, 140, 240, 360, 500]])

In [32]:
c/d

array([[0.1       , 0.1       , 0.1       , 0.1       , 0.1       ],
       [0.6       , 0.35      , 0.26666667, 0.225     , 0.2       ]])

In [33]:
#mencari akar dari array
np.sqrt(c)

array([[1.        , 1.41421356, 1.73205081, 2.        , 2.23606798],
       [2.44948974, 2.64575131, 2.82842712, 3.        , 3.16227766]])

In [34]:
#rumus exponensial
np.exp(c)

array([[2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
        1.48413159e+02],
       [4.03428793e+02, 1.09663316e+03, 2.98095799e+03, 8.10308393e+03,
        2.20264658e+04]])

In [35]:
#rumus sin
np.sin(c)

array([[ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427],
       [-0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849, -0.54402111]])

In [36]:
#menghitung log
np.log(c)

array([[0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791],
       [1.79175947, 1.94591015, 2.07944154, 2.19722458, 2.30258509]])

In [37]:
np.insert(c,5,100) #insert variabel setelah index ke-5

array([  1,   2,   3,   4,   5, 100,   6,   7,   8,   9,  10])

In [38]:
np.delete(c,2) #delete index ke-2

array([ 1,  2,  4,  5,  6,  7,  8,  9, 10])

In [39]:
np.append(c,150) #menambahkan variable sebagai index terakhir

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10, 150])

In [40]:
e = np.array([[1,2],[3,4]])
f = np.array([[5,6]])
np.concatenate((f,e),axis=0)

array([[5, 6],
       [1, 2],
       [3, 4]])

In [41]:
np.concatenate((e,f.T),axis = 1)

array([[1, 2, 5],
       [3, 4, 6]])

In [42]:
np.concatenate((e,f),axis = None)

array([1, 2, 3, 4, 5, 6])

In [43]:
#membuat kondisi, genap = kondisi jika memenuhi kondisi, ganjil = jika tidak memenuhi
np.where(c%2==0,'genap','ganjil')

array([['ganjil', 'genap', 'ganjil', 'genap', 'ganjil'],
       ['genap', 'ganjil', 'genap', 'ganjil', 'genap']], dtype='<U6')