In [39]:
import numpy as np

In [40]:
np.arange(1,30,3) #membuat array vector secara 1 = start value, 30 = max value, 3 = step/selisih

array([ 1,  4,  7, 10, 13, 16, 19, 22, 25, 28])

In [41]:
np.zeros((3,3,4)) #membuat array dengan variable = 0

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [42]:
np.ones((5,2)) #membuat array dengan variable = 1

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [43]:
np.eye(5) #membuat array dengan variable 1 dan 0, dimana variable 1 hanya muncul secara diagonal

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [44]:
np.linspace(0,20,100) #0 = nilai awal, 20 = nilai max, 5 = jml variable, setiap variable akan memiliki selisih yang sama

array([ 0.        ,  0.2020202 ,  0.4040404 ,  0.60606061,  0.80808081,
        1.01010101,  1.21212121,  1.41414141,  1.61616162,  1.81818182,
        2.02020202,  2.22222222,  2.42424242,  2.62626263,  2.82828283,
        3.03030303,  3.23232323,  3.43434343,  3.63636364,  3.83838384,
        4.04040404,  4.24242424,  4.44444444,  4.64646465,  4.84848485,
        5.05050505,  5.25252525,  5.45454545,  5.65656566,  5.85858586,
        6.06060606,  6.26262626,  6.46464646,  6.66666667,  6.86868687,
        7.07070707,  7.27272727,  7.47474747,  7.67676768,  7.87878788,
        8.08080808,  8.28282828,  8.48484848,  8.68686869,  8.88888889,
        9.09090909,  9.29292929,  9.49494949,  9.6969697 ,  9.8989899 ,
       10.1010101 , 10.3030303 , 10.50505051, 10.70707071, 10.90909091,
       11.11111111, 11.31313131, 11.51515152, 11.71717172, 11.91919192,
       12.12121212, 12.32323232, 12.52525253, 12.72727273, 12.92929293,
       13.13131313, 13.33333333, 13.53535354, 13.73737374, 13.93

In [45]:
np.random.rand(2,3,2) #membuat variable random float

array([[[0.48877705, 0.9709928 ],
        [0.0264234 , 0.61587839],
        [0.57899851, 0.71024933]],

       [[0.85410954, 0.57240303],
        [0.62264059, 0.3866902 ],
        [0.638276  , 0.03776576]]])

In [46]:
np.random.randn(3,3) #membuat variable random decimal negatif dan positif

array([[ 1.11925771, -0.57501206, -0.14426211],
       [-2.36548156,  1.27577629, -0.58203155],
       [-1.93288038,  0.05827127, -0.03677939]])

In [47]:
np.random.randint(2,50,3) #membuat variable random integer

array([19, 41, 13])

In [48]:
x = np.zeros((5,3))
x

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [49]:
x.shape #untuk mengetahui ukuran array

(5, 3)

In [50]:
y = x.reshape(3,5) #untuk mengubah ukuran array
y

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [51]:
z = x.reshape(-1) #untuk mengubah ukuran array menjadi vektor
z

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [52]:
a = np.random.randint(1,100,50)
a

array([23, 26, 39, 57, 30, 63, 59, 21, 63, 35, 75, 68, 60, 64, 35, 27, 69,
       14, 55, 76, 57, 43,  9, 91, 84, 29, 13, 73, 68, 23, 68, 10, 52, 39,
       29, 39, 70, 11,  6, 63, 99, 37, 20,  7, 12, 42, 53, 15,  2,  1])

In [53]:
a.max() #untuk mengetahui variabel max

99

In [54]:
a.argmax() #untuk mengetahui index dari variabel max

40

In [55]:
a.min() #untuk mengetahui variabel min

1

In [56]:
a.argmin() #untuk mengetahui index dari variabel min

49

In [57]:
a.dtype #untuk mengetahui tipe data dari suatu array

dtype('int32')

In [58]:
b = np.random.rand(2,3,2)
b

array([[[0.26253434, 0.38707761],
        [0.93404235, 0.37183051],
        [0.50133798, 0.0770932 ]],

       [[0.07693163, 0.72620366],
        [0.30528992, 0.64517445],
        [0.59084788, 0.02734843]]])

In [59]:
b.dtype

dtype('float64')

In [61]:
c = np.arange(0,11)
c

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [75]:
c[8] #mengambil nilai dari index ke-8

8

In [63]:
c[:5]#mengambil index awal sampai index ke-5

array([0, 1, 2, 3, 4])

In [66]:
c[0:6:2]#mengambil index 0:6 dengan selisih 2

array([0, 2, 4])

In [70]:
c[0:3] = 100 #merubah value variable dari range yang ditentukan
c

array([100, 100, 100,   3,   4,   5,   6,   7,   8,   9,  10])

In [71]:
c = np.arange(0,11)
c

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [72]:
d = c[0:6]
d

array([0, 1, 2, 3, 4, 5])

In [78]:
d[:] = 101 # [:]artinya merubah seluruh variable dalam array tsb
d

array([101, 101, 101, 101, 101, 101])

In [79]:
c #kalau pakai = maka original array nya akan berubah juga value nya

array([101, 101, 101, 101, 101, 101,   6,   7,   8,   9,  10])

In [80]:
e = c.copy() #supaya original array tidak berubah maka harus menggunakan .copy
e

array([101, 101, 101, 101, 101, 101,   6,   7,   8,   9,  10])

In [81]:
e[0:6]=6
e

array([ 6,  6,  6,  6,  6,  6,  6,  7,  8,  9, 10])

In [82]:
c

array([101, 101, 101, 101, 101, 101,   6,   7,   8,   9,  10])

In [85]:
f = np.random.randint(0,100,20) #create bilangan random integer
g = f.reshape(4,5) #ubah menjadi matrix 
g

array([[71, 96,  5, 42, 33],
       [24, 63, 73, 38, 58],
       [91, 84, 22,  4, 84],
       [32, 22, 70,  6, 64]])

In [86]:
g[1] #mencetak matrix index ke-1

array([24, 63, 73, 38, 58])

In [88]:
g[0][4] #mencetak baris index ke-0 dan kolom index ke-4

33

In [89]:
g[0,4] #mencetak baris index ke-0 dan kolom index ke-4

33

In [90]:
g[2:,3:] #mencetak baris index ke-2 sampai selesai dan kolom index ke-3 sampai selesai

array([[ 4, 84],
       [ 6, 64]])

In [93]:
#membuat array dengan variable yang tidak berurutan dan bisa dalam ukuran matrix yang bebas (fancy indexing)
[[g[2,3],g[2,4],g[3,3],g[3,4]],[g[2,3],g[2,4],g[3,3],g[3,4]]] 

[[4, 84, 6, 64], [4, 84, 6, 64]]

In [94]:
g>4 #kondisi true = >4 false = <4

array([[ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True, False,  True],
       [ True,  True,  True,  True,  True]])

In [95]:
#membuat variable bool_g untuk filtering di syntax berikutnya
bool_g = g>4
bool_g

array([[ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True, False,  True],
       [ True,  True,  True,  True,  True]])

In [96]:
g[bool_g] #filtering variable yang masuk kondisi bool_g

array([71, 96,  5, 42, 33, 24, 63, 73, 38, 58, 91, 84, 22, 84, 32, 22, 70,
        6, 64])

In [97]:
g[g<5]

array([4])

In [99]:
i = 30
g[g>i]

array([71, 96, 42, 33, 63, 73, 38, 58, 91, 84, 84, 32, 70, 64])